#!/bin/bash

doc=$1

pstexs=`find . -name \*.pstex`
if [ "x${pstexs}" != "x" ]
then
    for f in $pstexs ; do
        pdff=${f/.pstex/.pdf}
        if [ \( ! -f $pdff \) -o \( $f -nt $pdff \) ]
        then
            echo Processing $f...
            ps2pdf $f $pdff
            ft=${f/.pstex/.pstex_t/}
            sed -e 's/pstex/pdf/' $ft > ${ft/.pstex_t/.pdftex_t}
        fi
    done
fi

svgs=`find . -name \*.svg`
if [ "x${svgs}" != "x" ]
then
    for f in $svgs ; do
        epsf=${f/.svg/.eps}
        pdff=${f/.svg/.pdf}
        if [ \( ! -f $pdff \) -o \( $f -nt $pdff \) ]
        then
            echo Processing $f...
            inkscape --export-text-to-path --export-eps=$epsf $f
            epstopdf --outfile=$pdff $epsf
            /bin/rm $epsf
        fi
    done
fi

dtxf=$doc.dtx
texf=$doc.tex
bibf=$doc.bib

if [ \( ! -f $texf \) -o \( ! -f $bibf \) -o \
     \( $dtxf -nt $texf \) -o \( $dtxf -nt $bibf \) ]
then
    echo Rebuilding TeX source and bibliography files...
    if build-bib $doc.dtx $doc.tex
    then
        echo Bibliography built OK...
    else
        exit 1
    fi
fi

/bin/rm $doc.aux
pdflatex $doc.tex
bibtex $doc
pdflatex $doc.tex
pdflatex $doc.tex
